export { default as FloaterLarge } from './home/floater-large.svg'
export { default as MainLogoLight } from './logo/main-logo-light.svg'
export { default as MainLogoDark } from './logo/main-logo-dark.svg'
export { default as LongArrowRight } from './others/long-arrow-right.svg'
export { default as FloterSmallLight } from './others/floater-small-light.svg'
export { default as FloterSmallDark } from './others/floater-small-dark.svg'